package IGU;

/**
 *
 * @author Marcos
 */
public class Agenda extends javax.swing.JFrame {
    
        // Variables gloables
        int indexF = 0;

        public String[] contactOne = new String[6];
        public String[] contactTwo = new String[6];
        public String[] contactThree = new String[6];
        public String[] contactFour = new String[6];
        public String[] contactFive = new String[6];
        public String[] contactSix = new String[6];
        public String[] contactSeven = new String[6];
        public String[] contactEight = new String[6];
        public String[] contactNine = new String[6];
        public String[] contactTen = new String[6];

    public Agenda() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        titlePhoneBook = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        idField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        idLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        adressLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        birthDayLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        adressField = new javax.swing.JTextField();
        phoneNumberField = new javax.swing.JTextField();
        birthDayField = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        index = new javax.swing.JLabel();
        indexField = new javax.swing.JToggleButton();

        jTextField7.setText("jTextField1");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField11.setText("jTextField1");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlePhoneBook.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        titlePhoneBook.setForeground(new java.awt.Color(0, 0, 102));
        titlePhoneBook.setText("Agenda Electrónica");

        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        idLabel.setText("DNI");

        nameLabel.setText("Nombre");

        lastNameLabel.setText("Apellido");

        adressLabel.setText("Direccion");

        phoneNumberLabel.setText("Telefono");

        birthDayLabel.setText("F. Nac");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });

        adressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressFieldActionPerformed(evt);
            }
        });

        phoneNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberFieldActionPerformed(evt);
            }
        });

        birthDayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthDayFieldActionPerformed(evt);
            }
        });

        jLabel7.setText(":");

        jLabel8.setText(":");

        jLabel9.setText(":");

        jLabel10.setText(":");

        jLabel11.setText(":");

        jLabel12.setText(":");

        saveButton.setText("Grabar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        previousButton.setText("<<");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        nextButton.setText(">>");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        index.setText("Indice");

        indexField.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lastNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(idLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(adressLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adressField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(birthDayLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(phoneNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birthDayField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(85, 85, 85))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(titlePhoneBook))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(previousButton)
                            .addComponent(index))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(indexField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addComponent(nextButton)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(titlePhoneBook)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel)
                    .addComponent(adressLabel)
                    .addComponent(adressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameLabel)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(birthDayLabel)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthDayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(previousButton)
                    .addComponent(nextButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(index)
                    .addComponent(indexField))
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_idFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nameFieldActionPerformed

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void adressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_adressFieldActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void phoneNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_phoneNumberFieldActionPerformed

    private void birthDayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthDayFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_birthDayFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        indexF = Integer.parseInt(indexField.getText());
        
        String id = idField.getText();
        String firstName = nameField.getText();
        String lastName = lastNameField.getText();
        String adress = adressField.getText();
        String phoneNumber = phoneNumberField.getText();
        String birthDay = birthDayField.getText();
        
        switch(indexF){
            case 0:
                contactOne[0] = id;
                contactOne[1] = firstName;
                contactOne[2] = lastName;
                contactOne[3] = adress;
                contactOne[4] = phoneNumber;
                contactOne[5] = birthDay;
                break;
            case 1:
                contactTwo[0] = id;
                contactTwo[1] = firstName;
                contactTwo[2] = lastName;
                contactTwo[3] = adress;
                contactTwo[4] = phoneNumber;
                contactTwo[5] = birthDay;
                break;
            case 2:
                contactThree[0] = id;
                contactThree[1] = firstName;
                contactThree[2] = lastName;
                contactThree[3] = adress;
                contactThree[4] = phoneNumber;
                contactThree[5] = birthDay;
                break;
            case 3:
                contactFour[0] = id;
                contactFour[1] = firstName;
                contactFour[2] = lastName;
                contactFour[3] = adress;
                contactFour[4] = phoneNumber;
                contactFour[5] = birthDay;
                break;
            case 4:
                contactFive[0] = id;
                contactFive[1] = firstName;
                contactFive[2] = lastName;
                contactFive[3] = adress;
                contactFive[4] = phoneNumber;
                contactFive[5] = birthDay;
                break;
            case 5:
                contactSix[0] = id;
                contactSix[1] = firstName;
                contactSix[2] = lastName;
                contactSix[3] = adress;
                contactSix[4] = phoneNumber;
                contactSix[5] = birthDay;
                break;
            case 6:
                contactSeven[0] = id;
                contactSeven[1] = firstName;
                contactSeven[2] = lastName;
                contactSeven[3] = adress;
                contactSeven[4] = phoneNumber;
                contactSeven[5] = birthDay;
                break;
            case 7:
                contactEight[0] = id;
                contactEight[1] = firstName;
                contactEight[2] = lastName;
                contactEight[3] = adress;
                contactEight[4] = phoneNumber;
                contactEight[5] = birthDay;
                break;
            case 8:
                contactNine[0] = id;
                contactNine[1] = firstName;
                contactNine[2] = lastName;
                contactNine[3] = adress;
                contactNine[4] = phoneNumber;
                contactNine[5] = birthDay;
                break;
            case 9:
                contactTen[0] = id;
                contactTen[1] = firstName;
                contactTen[2] = lastName;
                contactTen[3] = adress;
                contactTen[4] = phoneNumber;
                contactTen[5] = birthDay;
                break;
        }
        
        

    }//GEN-LAST:event_saveButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        int currentIndex = Integer.parseInt(indexField.getText());
        int previousIndex;
        if(currentIndex > 0){
            previousIndex = currentIndex - 1;
        }else{
            previousIndex = currentIndex;
        }
        // Setear los campos
        switch(previousIndex){
            case 0:
                idField.setText(contactOne[0]);
                nameField.setText(contactOne[1]);
                lastNameField.setText(contactOne[2]);
                adressField.setText(contactOne[3]);
                phoneNumberField.setText(contactOne[4]);
                birthDayField.setText(contactOne[5]);
                indexField.setText("0");
                break;
            case 1:
                idField.setText(contactTwo[0]);
                nameField.setText(contactTwo[1]);
                lastNameField.setText(contactTwo[2]);
                adressField.setText(contactTwo[3]);
                phoneNumberField.setText(contactTwo[4]);
                birthDayField.setText(contactTwo[5]);
                indexField.setText("1");
                break;
            case 2:
                idField.setText(contactThree[0]);
                nameField.setText(contactThree[1]);
                lastNameField.setText(contactThree[2]);
                adressField.setText(contactThree[3]);
                phoneNumberField.setText(contactThree[4]);
                birthDayField.setText(contactThree[5]);
                indexField.setText("2");
                break;
            case 3:
                idField.setText(contactFour[0]);
                nameField.setText(contactFour[1]);
                lastNameField.setText(contactFour[2]);
                adressField.setText(contactFour[3]);
                phoneNumberField.setText(contactFour[4]);
                birthDayField.setText(contactFour[5]);
                indexField.setText("3");
                break;
            case 4:
                idField.setText(contactFive[0]);
                nameField.setText(contactFive[1]);
                lastNameField.setText(contactFive[2]);
                adressField.setText(contactFive[3]);
                phoneNumberField.setText(contactFive[4]);
                birthDayField.setText(contactFive[5]);
                indexField.setText("4");
                break;
            
            case 5:
                idField.setText(contactSix[0]);
                nameField.setText(contactSix[1]);
                lastNameField.setText(contactSix[2]);
                adressField.setText(contactSix[3]);
                phoneNumberField.setText(contactSix[4]);
                birthDayField.setText(contactSix[5]);
                indexField.setText("5");
                break;
            case 6:
                idField.setText(contactSeven[0]);
                nameField.setText(contactSeven[1]);
                lastNameField.setText(contactSeven[2]);
                adressField.setText(contactSeven[3]);
                phoneNumberField.setText(contactSeven[4]);
                birthDayField.setText(contactSeven[5]);
                indexField.setText("6");
                break;
            case 7:
                idField.setText(contactEight[0]);
                nameField.setText(contactEight[1]);
                lastNameField.setText(contactEight[2]);
                adressField.setText(contactEight[3]);
                phoneNumberField.setText(contactEight[4]);
                birthDayField.setText(contactEight[5]);
                indexField.setText("7");
                break;
            case 8:
                idField.setText(contactNine[0]);
                nameField.setText(contactNine[1]);
                lastNameField.setText(contactNine[2]);
                adressField.setText(contactNine[3]);
                phoneNumberField.setText(contactNine[4]);
                birthDayField.setText(contactNine[5]);
                indexField.setText("8");
                break;
            
            case 9:
                idField.setText(contactTen[0]);
                nameField.setText(contactTen[1]);
                lastNameField.setText(contactTen[2]);
                adressField.setText(contactTen[3]);
                phoneNumberField.setText(contactTen[4]);
                birthDayField.setText(contactTen[5]);
                indexField.setText("9");
                break;
            default:
                idField.setText(contactOne[0]);
                nameField.setText(contactOne[1]);
                lastNameField.setText(contactOne[2]);
                adressField.setText(contactOne[3]);
                phoneNumberField.setText(contactOne[4]);
                birthDayField.setText(contactOne[5]);
                indexField.setText("0");
                break;
        }
        
    }//GEN-LAST:event_previousButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        int currentIndex = Integer.parseInt(indexField.getText());
        int nextIndex;
        if(currentIndex < 9){
            nextIndex = currentIndex + 1;
        }else{
            nextIndex = currentIndex;
        }
        
        switch(nextIndex){
            case 0:
                idField.setText(contactOne[0]);
                nameField.setText(contactOne[1]);
                lastNameField.setText(contactOne[2]);
                adressField.setText(contactOne[3]);
                phoneNumberField.setText(contactOne[4]);
                birthDayField.setText(contactOne[5]);
                indexField.setText("0");
                break;
            case 1:
                idField.setText(contactTwo[0]);
                nameField.setText(contactTwo[1]);
                lastNameField.setText(contactTwo[2]);
                adressField.setText(contactTwo[3]);
                phoneNumberField.setText(contactTwo[4]);
                birthDayField.setText(contactTwo[5]);
                indexField.setText("1");
                break;
            case 2:
                idField.setText(contactThree[0]);
                nameField.setText(contactThree[1]);
                lastNameField.setText(contactThree[2]);
                adressField.setText(contactThree[3]);
                phoneNumberField.setText(contactThree[4]);
                birthDayField.setText(contactThree[5]);
                indexField.setText("2");
                break;
            case 3:
                idField.setText(contactFour[0]);
                nameField.setText(contactFour[1]);
                lastNameField.setText(contactFour[2]);
                adressField.setText(contactFour[3]);
                phoneNumberField.setText(contactFour[4]);
                birthDayField.setText(contactFour[5]);
                indexField.setText("3");
                break;
            case 4:
                idField.setText(contactFive[0]);
                nameField.setText(contactFive[1]);
                lastNameField.setText(contactFive[2]);
                adressField.setText(contactFive[3]);
                phoneNumberField.setText(contactFive[4]);
                birthDayField.setText(contactFive[5]);
                indexField.setText("4");
                break;
            
            case 5:
                idField.setText(contactSix[0]);
                nameField.setText(contactSix[1]);
                lastNameField.setText(contactSix[2]);
                adressField.setText(contactSix[3]);
                phoneNumberField.setText(contactSix[4]);
                birthDayField.setText(contactSix[5]);
                indexField.setText("5");
                break;
            case 6:
                idField.setText(contactSeven[0]);
                nameField.setText(contactSeven[1]);
                lastNameField.setText(contactSeven[2]);
                adressField.setText(contactSeven[3]);
                phoneNumberField.setText(contactSeven[4]);
                birthDayField.setText(contactSeven[5]);
                indexField.setText("6");
                break;
            case 7:
                idField.setText(contactEight[0]);
                nameField.setText(contactEight[1]);
                lastNameField.setText(contactEight[2]);
                adressField.setText(contactEight[3]);
                phoneNumberField.setText(contactEight[4]);
                birthDayField.setText(contactEight[5]);
                indexField.setText("7");
                break;
            case 8:
                idField.setText(contactNine[0]);
                nameField.setText(contactNine[1]);
                lastNameField.setText(contactNine[2]);
                adressField.setText(contactNine[3]);
                phoneNumberField.setText(contactNine[4]);
                birthDayField.setText(contactNine[5]);
                indexField.setText("8");
                break;
            
            case 9:
                idField.setText(contactTen[0]);
                nameField.setText(contactTen[1]);
                lastNameField.setText(contactTen[2]);
                adressField.setText(contactTen[3]);
                phoneNumberField.setText(contactTen[4]);
                birthDayField.setText(contactTen[5]);
                indexField.setText("9");
                break;
            default:
                idField.setText(contactOne[0]);
                nameField.setText(contactOne[1]);
                lastNameField.setText(contactOne[2]);
                adressField.setText(contactOne[3]);
                phoneNumberField.setText(contactOne[4]);
                birthDayField.setText(contactOne[5]);
                indexField.setText("0");
                break;
        }
    }//GEN-LAST:event_nextButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adressField;
    private javax.swing.JLabel adressLabel;
    private javax.swing.JTextField birthDayField;
    private javax.swing.JLabel birthDayLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel index;
    private javax.swing.JToggleButton indexField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton nextButton;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel titlePhoneBook;
    // End of variables declaration//GEN-END:variables
}
